join/urls.py
from django.conf.urls import url
from join import views

urlpatterns = [
    url(r'^$', views.index, name='join_submit'),

    url(r'^/handler/add', views.submit_handler_add, name='handler_submit_add'),

    url(r'^/edit$', views.edit_index, name='edit_index'),
    url(r'^/edit/detail', views.edit_detail, name='edit_handler'),
    url(r'^/handler/edit', views.edit_handler_save, name='handler_edit_save'),
]

signup/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^control', include('control.urls', namespace='control', app_name='control')),
    url(r'^join', include('join.urls', namespace='join', app_name='join')),
    url(r'', include('index.urls', namespace='index', app_name='index')),
    # url(r'^admin/', admin.site.urls),
]

join/models.py
from django.db import models

# Create your models here.
class People(models.Model):
    cid = models.TextField(max_length=20)
    name = models.TextField(default=' ')
    sex = models.CharField(max_length=4, default='男')
    classname = models.TextField(default=' ', null=True)
    phone = models.CharField(max_length=13)
    qq = models.CharField(max_length=15, null=True)
    mail = models.TextField(null=True)

    depart1 = models.TextField(default=' ')
    depart2 = models.TextField(default=' ')
    adjustment = models.BooleanField(default=True)

    hobby = models.TextField(null=True)
    experience = models.TextField(null=True)
    judge = models.TextField(null=True)

    created_time = models.DateTimeField(auto_now_add=True)
    last_modified_time = models.DateTimeField(auto_now=True)

join/views.py
from django.shortcuts import render
from join.models import People
from control.models import Config
from django.http import HttpResponse, HttpResponseNotFound

import random

key = ''

def genRandStr(length):
    str = ''
    elementstr = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    for x in range(0, length):
        str = str + elementstr[random.randint(0,len(elementstr)-1)]
    return str


# Create your views here.
def index(request):
    try:
        ifopen = Config.objects.get(name='ifopen')
        if ifopen.value == 'no':
            return HttpResponse(
                "<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'><title>提交失败</title><link rel='stylesheet' href='/static/join/css/save_success.css'></head><body bgcolor='#ebeae5'><div id='body'><h3>抱歉，线上报名已关闭</h3></div></body></html>")
    finally:
        1==1
    return render(request, 'join/form.html', {'page_type': 'new'})


def submit_handler_add(request):
    if request.method == 'POST':
        try:
            ifopen = Config.objects.get(name='ifopen')
            if ifopen.value == 'no':
                return HttpResponse("<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'><title>提交失败</title><link rel='stylesheet' href='/static/join/css/save_success.css'></head><body bgcolor='#ebeae5'><div id='body'><h3>抱歉，线上报名已关闭</h3></div></body></html>")
        finally:
            1==1
        existphone = People.objects.filter(phone=request.POST.get('phone'))
        existmail = People.objects.filter(mail=request.POST.get('mail'))
        if len(existphone) > 0 or len(existmail) > 0:
            return HttpResponse("<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'><title>提交失败</title><link rel='stylesheet' href='/static/join/css/save_success.css'></head><body bgcolor='#ebeae5'><div id='body'><h3>填写的电话或邮箱已经报过名了</h3></div></body></html>")

        rname = request.POST.get('name')
        phone = request.POST.get('phone')
        mail = request.POST.get('mail')

        if rname == '' or phone == '' or mail == '':
            return HttpResponse("<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'><title>提交失败</title><link rel='stylesheet' href='/static/join/css/save_success.css'></head><body bgcolor='#ebeae5'><div id='body'><h3>姓名、电话或邮箱为空</h3></div></body></html>")

        people = People()
        people.cid = genRandStr(16)
        people.name = request.POST.get('name')
        people.sex = request.POST.get('sex')
        people.classname = request.POST.get('classname')
        people.phone = request.POST.get('phone')
        people.qq = request.POST.get('qq')
        people.mail = request.POST.get('mail')

        people.depart1 = request.POST.get('depart1')
        people.depart2 = request.POST.get('depart2')
        if request.POST.get('adjustment')=='on':
            people.adjustment = True
        else:
            people.adjustment = False

        people.hobby = request.POST.get('hobby')
        people.experience = request.POST.get('experience')
        people.judge = request.POST.get('judge')
        people.save()

        return render(request, 'join/save_success.html')

    else:
        return HttpResponseNotFound("<h2>Page Not Found</h2>")


def edit_index(request):
    return render(request, 'join/edit_login.html')


def edit_detail(request):
    if request.method == 'POST':
        people = People.objects.filter(name=request.POST.get('name'))
        people = people.filter(phone=request.POST.get('phone'))
        if len(people) == 1:
            return render(request, 'join/form.html', {'page_type': 'edit', 'data': people[0]})
        else:
            return HttpResponse("<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'><title>错误</title><link rel='stylesheet' href='/static/join/css/save_success.css'></head><body bgcolor='#ebeae5'><div id='body'><h3>没有找到对应信息</h3></div></body></html>")
    else:
        return HttpResponseNotFound("<h2>Page Not Found</h2>")


def edit_handler_save(request):
    if request.method == 'POST':
        try:
            ifopen = Config.objects.get(name='ifopen')
            if ifopen.value == 'no':
                return HttpResponse(
                    "<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'><title>提交失败</title><link rel='stylesheet' href='/static/join/css/save_success.css'></head><body bgcolor='#ebeae5'><div id='body'><h3>抱歉，线上报名已关闭</h3></div></body></html>")
        finally:
            1==1
        people = People.objects.get(cid=request.POST.get('cid'))
        if people.name == request.POST.get('name') and people.phone == request.POST.get('phone'):
            people.sex = request.POST.get('sex')
            people.classname = request.POST.get('classname')
            people.qq = request.POST.get('qq')

            people.depart1 = request.POST.get('depart1')
            people.depart2 = request.POST.get('depart2')
            if request.POST.get('adjustment')=='on':
                people.adjustment = True
            else:
                people.adjustment = False

            people.hobby = request.POST.get('hobby')
            people.experience = request.POST.get('experience')
            people.judge = request.POST.get('judge')
            people.save()

        else:
            return HttpResponseNotFound("<h2>Page Not Found</h2>")

        return render(request, 'join/save_success.html')

    else:
        return HttpResponseNotFound("<h2>Page Not Found</h2>")

join/templates/join/edit_login.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>修改信息</title>
    <link rel="stylesheet" href="/static/join/css/save_success.css">
    <style>
        * {
            font-family: 微软雅黑;
        }
        input {
            background: transparent;
	        border: 0px;
            border-bottom: #d2d2d2 2px solid;
            font-size: 16px;
            line-height: 24px;
        }
        .input-group {
            padding-bottom: 10px;
        }
    </style>
</head>

<body bgcolor="#ebeae5">
<div id="body">
	<center>
	 <h1>修改信息</h1>
	 <form action="{% url 'join:edit_handler' %}" method="post">
        <div class="input-group">
            <label for="">姓名</label><input type="text" name="name">
        </div>
        <div class="input-group">
            <label for="">电话</label><input type="text" name="phone">
        </div>
        {% csrf_token %}
        <div>
            <button type="submit">确定</button>
        </div>
    </form>
	</center>
</div>
</body>
</html>

join/templates/join/error.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>出错啦</title>
</head>
<body>
抱歉，我们这儿出现了一些问题
</body>
</html>

join/templates/join/form.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>填写报名信息</title>
    <link rel="stylesheet" href="/static/join/css/form.css">
</head>
<body bgcolor="#ebeae5">
<div id="body">
<form action="{% if page_type == 'new' %}{% url 'join:handler_submit_add' %}{% elif page_type == 'edit' %}{% url 'join:handler_edit_save' %}{% endif %}" method="post">
    <!-- Input page -->
    <div id="input_page">
        <h1 align="center">信息填写</h1>
        <hr>
        {% if page_type == 'edit' %}
            <input name="cid" type="hidden" value="{{ data.cid }}">
            <input type="hidden" name="name" value="{{ data.name }}">
            <input type="hidden" name="phone" value="{{ data.phone }}">
        {% endif %}

        <div>
            <label for="name_input">姓名：</label>
            {% if page_type == 'new' %}
                <input type="text" name="name" id="name_input">
                {% elif page_type == 'edit' %}
                {{ data.name }}<input type="hidden" name="name" id="name_input" value="{{ data.name }}">
            {% endif %}
        </div>

        <div>
            <label for="sex_input">性别：</label>
            <select name="sex" id="sex_input">
                <option value="男" {% if page_type == 'new' or data.sex == '男' %}selected{% endif %}>男</option>
                <option value="女" {% if data.sex == '女' %}selected{% endif %}>女</option>
            </select>
        </div>

        <div>
            <label for="class1_input">专业班级：</label>
            <input style="width:55%; font-size:20px;" type="text" name="classname"{% if page_type == 'edit' %} value="{{ data.classname }}"{% endif %} id="class1_input">
        </div>

        <div>
            <label for="dream_input1">意向部门1：</label>
            <select name="depart1" id="dream_input1">
                <option value=""{% if page_type == 'new' %} selected{% endif %}>(请选择)</option>
                <option value="财务部"{% if data.depart1 == '财务部' %} selected{% endif %}>财务部</option>
                <option value="社团外联企划部"{% if data.depart1 == '社团外联企划部' %} selected{% endif %}>社团外联企划部</option>
                <option value="秘书部"{% if data.depart1 == '秘书部' %} selected{% endif %}>秘书部</option>
                <option value="人力资源部"{% if data.depart1 == '人力资源部' %} selected{% endif %}>人力资源部</option>
                <option value="社团部"{% if data.depart1 == '社团部' %} selected{% endif %}>社团部</option>
                <option value="行政监察部"{% if data.depart1 == '行政监察部' %} selected{% endif %}>行政监察部</option>
                <option value="外联部"{% if data.depart1 == '外联部' %} selected{% endif %}>外联部</option>
                <option value="公共关系部"{% if data.depart1 == '公共关系部' %} selected{% endif %}>公共关系部</option>
                <option value="思存工作室"{% if data.depart1 == '思存工作室' %} selected{% endif %}>思存工作室</option>
                <option value="新媒体工作室"{% if data.depart1 == '新媒体工作室' %} selected{% endif %}>新媒体工作室</option>
                <option value="宣传部"{% if data.depart1 == '宣传部' %} selected{% endif %}>宣传部</option>
                <option value="媒体部"{% if data.depart1 == '媒体部' %} selected{% endif %}>媒体部</option>
                <option value="文艺拓展部"{% if data.depart1 == '文艺拓展部' %} selected{% endif %}>文艺拓展部</option>
            </select>
        </div>

        <div>
            <label for="dream_input2">意向部门2：</label>
            <select name="depart2" id="dream_input2">
                <option value=""{% if page_type == 'new' %} selected{% endif %}>(请选择)</option>
                <option value="财务部"{% if data.depart2 == '财务部' %} selected{% endif %}>财务部</option>
                <option value="社团外联企划部"{% if data.depart2 == '社团外联企划部' %} selected{% endif %}>社团外联企划部</option>
                <option value="秘书部"{% if data.depart2 == '秘书部' %} selected{% endif %}>秘书部</option>
                <option value="人力资源部"{% if data.depart2 == '人力资源部' %} selected{% endif %}>人力资源部</option>
                <option value="社团部"{% if data.depart2 == '社团部' %} selected{% endif %}>社团部</option>
                <option value="行政监察部"{% if data.depart2 == '行政监察部' %} selected{% endif %}>行政监察部</option>
                <option value="外联部"{% if data.depart2 == '外联部' %} selected{% endif %}>外联部</option>
                <option value="公共关系部"{% if data.depart2 == '公共关系部' %} selected{% endif %}>公共关系部</option>
                <option value="思存工作室"{% if data.depart2 == '思存工作室' %} selected{% endif %}>思存工作室</option>
                <option value="新媒体工作室"{% if data.depart2 == '新媒体工作室' %} selected{% endif %}>新媒体工作室</option>
                <option value="宣传部"{% if data.depart2 == '宣传部' %} selected{% endif %}>宣传部</option>
                <option value="媒体部"{% if data.depart2 == '媒体部' %} selected{% endif %}>媒体部</option>
                <option value="文艺拓展部"{% if data.depart2 == '文艺拓展部' %} selected{% endif %}>文艺拓展部</option>
            </select>
        </div>

        <div>
            <label for="adjustment_input">是否服从调剂：</label>
            <input type="checkbox" id="adjustment_input" name="adjustment"{% if page_type == 'new' or data.adjustment == True %}checked{% endif %}>
        </div>

        <div>
            <label for="qq_input">QQ：</label>
            <input type="text" name="qq" {% if page_type == 'edit' %}value="{{ data.qq }}"{% endif %} id="qq_input" onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')">
        </div>

        <div>
            <label for="tel_input">电话：</label>
            {% if page_type == 'new' %}
            <input type="text" name="phone" id="tel_input" onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')">
            {% elif page_type == 'edit' %}
                <input type="hidden" value="{{ data.phone }}" name="phone" id="tel_input">{{ data.phone }}
            {% endif %}
        </div>

        <div>
            <label for="email_input">EMAIL：</label>
            {% if page_type == 'new' %}
            <input type="text" name="mail" id="email_input">
            {% elif page_type == 'edit' %}
                <input type="hidden" value="{{ data.mail }}" name="mail" id="email_input">{{ data.mail }}
            {% endif %}
        </div>

        <br>

        <h2>我们还想更多的了解下你...</h2>
        <div id="comment_input">
            <div>
                <h3>少侠有哪些特长呢？</h3>
                <textarea name="hobby" id="special_input" rows="4">{% if page_type == 'edit' %}{{ data.hobby }}{% endif %}</textarea>
            </div>
            <div>
                <h3>有什么实践经历吗？</h3>
                <textarea name="experience" id="experience_input" rows="4">{% if page_type == 'edit' %}{{ data.experience }}{% endif %}</textarea>
            </div>
            <div>
                <h3>少侠评价一下自己吧：</h3>
                <textarea name="judge" id="self_input" rows="4">{% if page_type == 'edit' %}{{ data.judge }}{% endif %}</textarea>
            </div>
        </div>
        <center><button id="next" type="button">下一步</button></center>
    </div>
    <!-- Input page ends -->

    <!--Confirm page-->
    <div id="confirm_page" class="pages" style="display:none">
        <h1 align="center">确认信息</h1>
        <hr>
        <br>
        <div class="infor">
            姓名：<a id="name" name="name" href="#" onClick="back1()"></a>
        </div>
        <div class="infor">
            性别：<a id="sex" name="sex" href="#" onClick="back1()"></a>
        </div>

        <div class="infor">
            专业班级：<a id="class1" name="class1" href="#" onClick="back1()" style="font-size:20px"></a>
        </div>

        <div class="infor">
            意向部门1：<a id="depart1" name="intension" href="#" onClick="back1()"></a>
        </div>

        <div class="infor">
            意向部门2：<a id="depart2" name="intension" href="#" onClick="back1()"></a>
        </div>

        <div class="infor">
            是否服从调剂：<a id="change" name="change" href="#" onClick="back1()"></a>
        </div>

        <div class="infor">
            QQ:<a id="qq" name="qq" href="#" onClick="back1()"></a>
        </div>

        <div class="infor">
            TEL:<a id="tel" name="tel" href="#" onClick="back1()"></a>
        </div>

        <div class="infor">
            EMAIL：<a id="email" name="email" href="#" onClick="back1()"></a>
        </div>

        <br>

        {% csrf_token %}
        <div id="confirm">
           <button style="float:right;" id="confirm_submit">已阅，提交</button>
        </div>
    </div>
        <!--Confirm page end-->
</form>
</div>


<script type="text/javascript" src="/static/join/js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="/static/join/js/form.js"></script>
</body>
</html>

join/templates/join/save_success.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>报名成功</title>
    <link rel="stylesheet" href="/static/join/css/save_success.css">
</head>

<body bgcolor="#ebeae5">
<div id="body">
	<center>
	  <h1>报名成功</h1>
	  <img src="/static/index/img/hero.png" width="70%" style="margin:30px auto;">
	  <h2>我们期待与你们相遇</h2>
	  <div id="bottom"><div><img src="/static/join/img/ironman.png" height="150px"></div><div id="welcome">社联风采<br>一睹为快</div></div>
	</center>
</div>
</body>
</html>