index/urls.py
from django.conf.urls import url
from index import views

urlpatterns = [
    url(r'^intro$', views.intro_index, name='intro_index'),
    url(r'^intro/(?P<depart>\w+)', views.intro_depart),
    url(r'^', views.index, name='index'),

]

join/urls.py
from django.conf.urls import url
from join import views

urlpatterns = [
    url(r'^$', views.index, name='join_submit'),

    url(r'^/handler/add', views.submit_handler_add, name='handler_submit_add'),

    url(r'^/edit$', views.edit_index, name='edit_index'),
    url(r'^/edit/detail', views.edit_detail, name='edit_handler'),
    url(r'^/handler/edit', views.edit_handler_save, name='handler_edit_save'),
]

signup/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^control', include('control.urls', namespace='control', app_name='control')),
    url(r'^join', include('join.urls', namespace='join', app_name='join')),
    url(r'', include('index.urls', namespace='index', app_name='index')),
    # url(r'^admin/', admin.site.urls),
]

index/templates/index/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>学生社团联合会秋季招新</title>
    <link rel="stylesheet" href="/static/index/css/index.css">
</head>
<body bgcolor="#ebeae5">
<div id="body">
	<center>
		<h1>学生社团联合会秋季招新</h1>
		<h1 class="en">IF YOU WANT TO BE<br>
			A HERO</h1>
		<img src="/static/index/img/hero.png">
		<h1 class="en">JOIN US NOW</h1>
		<div id="bottom">
            <table style="width: 95%; text-align: center">
                <tr>
                    <td width="33%">
                        <a href="{% url 'index:intro_index' %}">围观</a>
                    </td>
                    <td width="33%">
                        <a href="{% url 'join:edit_index' %}">查询</a>
                    </td>
                    <td width="33%">
                        <a href="{% url 'join:join_submit' %}">报名</a>
                    </td>
                </tr>
            </table>
        </div>
	</center>
</div>
</body>
</html>